// Generated by CoffeeScript 1.9.3
(function() {
  define(function() {
    'use strict';
    return function(match) {
      match('library', 'library#books');
      return match('profile', 'library#profile');
    };
  });

}).call(this);
