// Generated by CoffeeScript 1.9.3
(function() {
  define([], function() {
    'use strict';
    var ResourceManager;
    return ResourceManager = (function() {
      var storage;

      function ResourceManager() {}

      storage = {};

      ResourceManager.store = function(name, init) {
        if (!name) {
          return;
        }
        if (!init) {
          return;
        }
        if (typeof init === "function" ? init() : void 0) {
          return storage[name] = init();
        } else {
          return storage[name] = init;
        }
      };

      ResourceManager.get = function(name) {
        return storage[name];
      };

      ResourceManager.dispose = function(args) {};

      return ResourceManager;

    })();
  });

}).call(this);
