// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['chaplin', 'views/base/view'], function(Chaplin, View) {
    'use strict';
    var CollectionView;
    return CollectionView = (function(superClass) {
      extend(CollectionView, superClass);

      function CollectionView() {
        return CollectionView.__super__.constructor.apply(this, arguments);
      }

      CollectionView.prototype.getTemplateFunction = View.prototype.getTemplateFunction;

      CollectionView.prototype.renderAll = function() {
        return this.subviews.forEach(function(item) {
          return item.render();
        });
      };

      return CollectionView;

    })(Chaplin.CollectionView);
  });

}).call(this);
