// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['views/base/collection-view', 'text!templates/books.hbs', 'views/book-view'], function(CollectionView, template, BookView) {
    'use strict';
    var BooksView;
    return BooksView = (function(superClass) {
      extend(BooksView, superClass);

      function BooksView() {
        return BooksView.__super__.constructor.apply(this, arguments);
      }

      BooksView.prototype.template = template;

      template = null;

      BooksView.prototype.autoRender = true;

      BooksView.prototype.className = 'books';

      BooksView.prototype.itemView = BookView;

      return BooksView;

    })(CollectionView);
  });

}).call(this);
