// Generated by CoffeeScript 1.9.3
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['views/base/view', 'text!templates/library.hbs', 'views/modal-view-factory', 'handlebars'], function(View, template, BookViewFactory, Handlebars) {
    'use strict';
    var LibraryView;
    return LibraryView = (function(superClass) {
      extend(LibraryView, superClass);

      function LibraryView() {
        this.addBook = bind(this.addBook, this);
        return LibraryView.__super__.constructor.apply(this, arguments);
      }

      LibraryView.prototype.template = template;

      template = null;

      LibraryView.prototype.autoRender = true;

      LibraryView.prototype.className = 'library';

      LibraryView.prototype.events = {
        'click .add-book': 'showModalBook'
      };

      LibraryView.prototype.initialize = function() {
        LibraryView.__super__.initialize.apply(this, arguments);
        this.showAttributes = {
          name: true,
          title: true,
          author: true,
          description: true,
          price: true
        };
        this.visible = 5;
        Handlebars.registerHelper('attr-show', (function(_this) {
          return function(cond) {
            return cond.fn(_this.showAttributes);
          };
        })(this));
        Handlebars.registerHelper('short', (function(_this) {
          return function(value) {
            var result;
            result = value.substring(0, 50 / _this.visible);
            if (result.length < value.length) {
              result += '...';
            }
            return result;
          };
        })(this));
        return Handlebars.registerHelper('width', (function(_this) {
          return function() {
            return 670 / _this.visible + 'px';
          };
        })(this));
      };

      LibraryView.prototype.addBook = function(book) {
        return this.subviewsByName['books'].collection.addBook(book);
      };

      LibraryView.prototype.showModalBook = function() {
        return BookViewFactory.createBook(this.addBook);
      };

      LibraryView.prototype.applyFilter = function(profiles) {
        var i, len, profile;
        if (profiles.length > 0) {
          delete this.showAttributes;
          this.showAttributes = {};
          this.visible = 0;
          for (i = 0, len = profiles.length; i < len; i++) {
            profile = profiles[i];
            if (!!profile.attributes.is_visible) {
              this.visible++;
            }
            this.showAttributes[profile.attributes.column_name.toLowerCase()] = profile.attributes.is_visible;
          }
        }
        this.render();
        this.subviewsByName['books'].render();
        return this.subviewsByName['books'].collection.reset(this.subviewsByName['books'].collection.toJSON());
      };

      return LibraryView;

    })(View);
  });

}).call(this);
