// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['views/base/view', 'text!templates/options.hbs'], function(View, template) {
    'use strict';
    var OptionsView;
    return OptionsView = (function(superClass) {
      extend(OptionsView, superClass);

      function OptionsView() {
        return OptionsView.__super__.constructor.apply(this, arguments);
      }

      OptionsView.prototype.template = template;

      template = null;

      OptionsView.prototype.autoRender = true;

      OptionsView.prototype.className = 'options';

      return OptionsView;

    })(View);
  });

}).call(this);
