// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['chaplin', 'views/base/view', 'text!templates/site.hbs'], function(Chaplin, View, template) {
    'use strict';
    var SiteView;
    return SiteView = (function(superClass) {
      extend(SiteView, superClass);

      function SiteView() {
        return SiteView.__super__.constructor.apply(this, arguments);
      }

      SiteView.prototype.container = 'body';

      SiteView.prototype.id = 'site-container';

      SiteView.prototype.regions = {
        content: '#content-container',
        books: '#books-container',
        profiles: '#profiles-container'
      };

      SiteView.prototype.template = template;

      template = null;

      SiteView.prototype.events = {
        'click .library': 'goLibrary',
        'click .profile': 'goProfile'
      };

      SiteView.prototype.goLibrary = function() {
        return Chaplin.utils.redirectTo('library#books');
      };

      SiteView.prototype.goProfile = function() {
        return Chaplin.utils.redirectTo('library#profile');
      };

      return SiteView;

    })(View);
  });

}).call(this);
