// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['chaplin', 'models/base/model'], function(Chaplin, Model) {
    'use strict';
    var Book;
    return Book = (function(superClass) {
      extend(Book, superClass);

      function Book() {
        return Book.__super__.constructor.apply(this, arguments);
      }

      Book.prototype.defaults = {
        message: 'Hello World!'
      };

      return Book;

    })(Model);
  });

}).call(this);
