// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['chaplin', 'models/base/collection', 'models/profile'], function(Chaplin, Collection, Profile) {
    'use strict';
    var Profiles;
    return Profiles = (function(superClass) {
      extend(Profiles, superClass);

      function Profiles() {
        return Profiles.__super__.constructor.apply(this, arguments);
      }

      Profiles.prototype.model = Profile;

      Profiles.prototype.url = '/api/profiles/';

      Profiles.prototype.parse = function(data) {
        return data.objects;
      };

      Profiles.prototype.initialize = function() {
        Profiles.__super__.initialize.apply(this, arguments);
        return this.sort();
      };

      Profiles.prototype.comparator = function(model) {
        return model.get('column_name');
      };

      return Profiles;

    })(Collection);
  });

}).call(this);
